[tool.poetry]
name = "llama-projects"
version = "0.1.0"
description = "Unified project for Llama fine-tuning, RAG, and dataset building"
authors = ["Lorenzo Massone <lorenzo.massone@studio.unibo.it>"]

[tool.pyright]
include = ["src"]                                        # Directories to include in type checking
exclude = ["**/node_modules", "**/__pycache__", "**/.*"]
ignore = []                                              # Paths to ignore

# Type checking mode
typeCheckingMode = "off" # Can be "off", "basic", or "strict"

[tool.poetry.dependencies]
python = "^3.9"
# Core ML dependencies
torch = "^2.0.0"
transformers = "^4.36.0"
datasets = "^2.16.0"
unsloth = { git = "https://github.com/unslothai/unsloth.git" }
bitsandbytes = "^0.41.3"
trl = "^0.7.6"

# RAG and data processing
langchain = "*"
langchain-core = "*"
langchain-community = "*"
ollama = "^0.1.0"
chromadb = "^0.4.0"

# Utilities
pandas = "^2.0.0"
nltk = "^3.8.1"
beautifulsoup4 = "^4.12.0"
gradio = "^4.0.0"
crystalbleu = "^0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
jupyter = "^1.0.0"
ipykernel = "^6.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
